import os
import subprocess
import shutil
from datetime import datetime

def build_project(build_profile="debug", clean=False):
    """
    Builds the project in the specified mode (debug/release) and optionally cleans prior builds.
    """
    print(f"[INFO] Building project in {build_profile} mode")

    if clean:
        print("Cleaning previous builds...")
        if os.path.exists("target"):
            shutil.rmtree("target")
            print("✅ Cleaned previous builds")

    build_flags = ["--release"] if build_profile == "release" else []
    try:
        subprocess.run(["cargo", "build"] + build_flags, check=True, text=True)
        print("✅ Build completed successfully!")
    except subprocess.CalledProcessError:
        print("❌ Project build failed!")
        return False

    return True

def copy_binaries(build_profile, release_dir):
    """
    Copies the binaries to the release directory.
    """
    binaries = [
        {"name": "dryad.exe", "description": "Dryad Language Interpreter"},
        {"name": "oak.exe", "description": "Oak Tool"},
        {"name": "benchmark.exe", "description": "Dryad Benchmark Tool"},
    ]

    print(f"📂 Copying binaries to {release_dir}...")

    os.makedirs(release_dir, exist_ok=True)
    copied_count = 0

    for binary in binaries:
        source_path = os.path.join("target", build_profile, binary["name"])
        dest_path = os.path.join(release_dir, binary["name"])

        if os.path.isfile(source_path):
            shutil.copy2(source_path, dest_path)
            size = os.path.getsize(dest_path) / (1024 * 1024)
            print(f"✅ {binary['description']} copied ({size:.2f} MB)")
            copied_count += 1
        else:
            print(f"⚠️  {binary['description']} not found: {source_path}")

    print(f"Total binaries copied: {copied_count}")

    return copied_count

def copy_docs(release_dir):
    """
    Copies important documentation files to the release directory.
    """
    docs = ["README.md", "benchmark.md", "DRYAD_ERROR_GUIDE.md"]

    print("📚 Copying documentation files...")

    for doc in docs:
        if os.path.isfile(doc):
            dest_path = os.path.join(release_dir, os.path.basename(doc))
            shutil.copy2(doc, dest_path)
            print(f"✅ {doc} copied")
        else:
            print(f"⚠️  {doc} not found (optional)")

def generate_build_info(release_dir, build_profile):
    """
    Generates a build information file.
    """
    build_info_path = os.path.join(release_dir, "BUILD_INFO.md")
    build_info = f"""
# Dryad Language Release Information

**Build Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Build Profile:** {build_profile}
**Rust Version:** {subprocess.run(['rustc', '--version'], capture_output=True, text=True).stdout.strip()}
**Build Machine:** {os.environ.get('COMPUTERNAME', 'Unknown')}
**Build User:** {os.environ.get('USERNAME', 'Unknown')}

## Included Binaries
- `dryad.exe`: Dryad Language Interpreter
- `oak.exe`: Oak Tool
- `benchmark.exe`: Dryad Benchmark Tool

---
This release was automatically generated by the build_release.py script.
"""
    with open(build_info_path, "w", encoding="utf-8") as file:
        file.write(build_info)

    print(f"✅ Build information saved to {build_info_path}")

def main():
    import argparse

    parser = argparse.ArgumentParser(description="Automated build and release script for Dryad")
    parser.add_argument("--debug", action="store_true", help="Build in debug mode (default)")
    parser.add_argument("--release", action="store_true", help="Build in release mode")
    parser.add_argument("--clean", action="store_true", help="Clean previous builds before building")
    parser.add_argument("--output", type=str, default="dryad_release", help="Output directory for the release")

    args = parser.parse_args()

    build_profile = "release" if args.release else "debug"
    release_dir = args.output

    if build_project(build_profile, args.clean):
        copy_binaries(build_profile, release_dir)  # Pass build_profile explicitly
        copy_docs(release_dir)
        generate_build_info(release_dir, build_profile)  # Pass build_profile explicitly

        print(f"🎉 Release created successfully at: {release_dir}")
    else:
        print("❌ Release creation failed.")

if __name__ == "__main__":
    main()